# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161107_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_system_acount',
        ),
    ]
