# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_has_system_acount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_system_acount',
        ),
    ]
